# Generated by Django 2.2.4 on 2019-08-11 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20190811_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
