# Generated by Django 2.2.4 on 2019-08-11 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0010_event_guest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='guest',
            name='event',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Guest',
        ),
    ]
